library(tidyverse)

#Input for this script is the datafile generated by the function --genome of Plink
setwd("~/Documents/Extra_GRSM/IBD")
genome1<-read.table("IBD_GRSM.genome",header=T) #Load total population
genome1$dataid<-"GRSM"
genome1<-select(genome1,PI_HAT,dataid)

genome2<-read.table("IBD_Swain.genome",header=T) #load subpopulation 1
genome2$dataid<-"Swain"
genome2<-select(genome2,PI_HAT,dataid)

genome3<-read.table("IBD_Blount.genome",header=T) #load subpopulation 2
genome3$dataid<-"Blount"
genome3<-select(genome3,PI_HAT,dataid)

genome<-rbind(genome1,genome2,genome3)

ggplot(data=genome,aes(PI_HAT,color=dataid))+geom_density(size=1.1, key_glyph="path")+labs(x="Proportion IBD",y="Density")+
  scale_x_continuous(expand = c(0, 0), limits = c(0, 0.6))+ 
  scale_y_continuous(expand = c(0, 0), limits = c(0, 8))+labs(x="Proportion IBD",y="Density")+
  theme_classic(base_size = 20)+theme(axis.text.x = element_text(colour = "black"),axis.text.y = element_text(colour = "black"))+
  theme(legend.position = c(0.15, 0.8))+theme(legend.position = c(0.85, 0.8))+ labs(color='Population ID') 
setwd("/home/barmentarier/Documents/FIGURES_FOR_RESULTS")
ggsave("Suppl_IBD.png",dpi=900)
