library(tidyverse)
library(ggplot2)

#input for this script is are the plink files generated by the --pca command
setwd("~/Documents/Extra_GRSM/pca")
pca <- read_table2("pca_GRSM_537.eigenvec", col_names = FALSE)
eigenval <- scan("pca_GRSM_537.eigenval")

# set names
names(pca)[1] <- "ind"
names(pca)[2]<-"IID"
names(pca)[3:ncol(pca)] <- paste0("PC", 1:(ncol(pca)-2))
pca <- pca %>% select(ind,IID,PC1,PC2)
pca$ind <- as.character(pca$ind)
pca$FID<-pca$ind
pca$FID<-as.character(pca$FID)
pca$FID[pca$FID=="Sewer"]<-"Sevier"
pve <- data.frame(PC = 1:20, pve = eigenval/sum(eigenval)*100) #Generate the amount of variance explained for each of the top twenty PCs


# plot pca
col<-c("#FECC5C" ,"#FD8D3C", "#F03B20","red", "#BD0026")
b <- ggplot(pca, aes(PC1, PC2, color = FID)) + geom_point(size = 2)
b <- b + coord_equal() + 
  theme_classic(base_size = 15)+theme(axis.text.x = element_text(colour = "black"),axis.text.y = element_text(colour = "black"))
b + xlab(paste0("PC1 (", signif(pve$pve[1], 3), "%)")) + 
  ylab(paste0("PC2 (", signif(pve$pve[2], 3), "%)"))+ 
  scale_color_manual(name="Population ID",values=col)+xlim(-0.15,0.1)+ylim(-0.15,0.1)
setwd("~/Documents/FIGURES_FOR_RESULTS")
ggsave("PCA_GRSM.png")  

